### ISSUE TITLE
@dmitrij176 to include the best Whitgift sample received to date for shipment to @wwjvdsande. @kym834 has already given it a MyOS code and added it to the Master List.

### ISSUE THREAD

**Issue by dmitrij176** [OpenSourceMycetoma/Monthly-zoom-meetings#11]
@kym834 I am looking for MYOS codes assigned to Whitgift compounds, but could not find them on the MasterList.
Can you please help me find them.
From the action item for the upcoming MycetOS meeting (29.08.23) these molecules have already been given their unique IDs.
Let me know.
Thanks in advance

**Comment by kym834** [comment]
Compound they made is MYOS_00429_00_01
