### ISSUE TITLE
World NTD Day on January 30th - ideas for promoting MycetOS projects 

### ISSUE THREAD

**Issue by KlementineJBS** [OpenSourceMycetoma/Monthly-zoom-meetings#16]
Please share your ideas on how to promote the projects for World NTD Day. 

If your institution has written a press release / social media post, please share that here too so that we can all promote it through our own networks.

**Comment by wwjvdsande** [comment]
For twitter/x we can use this: #mycetoma is a devastating skin disease that can lead to stigma, disability, & amputation and for which no proper medications are available. The open source drug discovery project #MycetOS uses open science to develop novel drugs for mycetoma and everyone can help. Join us at https://github.com/OpenSourceMycetoma #WorldNTDDay

**Comment by MFernflower** [comment]
Was just curious what happened with this

**Comment by mattodd** [comment]
Tweet sent. Have installed link to this at https://github.com/OpenSourceMycetoma/Talks-Meetings-Publicity/wiki/Publicity-on-Themed-Days so can close this Issue. Would be nice to do more, but bandwidth always an issue. Let's all keep an eye out for other opportunities to highlight what we're doing. Wendy and I are on the CDC-led Global Mycetoma Working Group, which can also be used to promote.
